baseurl = "/"
title = "Sabir Ansari | Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Sabir Ansari"
    description = "Desktop Supper Engineer | Developer | Technical Writer "
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/sabir_ansari95"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"